# Generated by Django 3.1 on 2020-08-26 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Back_pic',
            new_name='back_pic',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Front_pic',
            new_name='front_pic',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Name',
            new_name='name',
        ),
    ]
